import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#3b4d09',
        'on-secondary-container': '#566a25',
        'error-container': '#ffdad6',
        'surface-tint': '#416658',
        'surface-variant': '#e2e3de',
        'on-surface': '#1a1c19',
        secondary: '#526521',
        'surface-dim': '#d9dad6',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#b6ccba',
        'tertiary-fixed': '#d2e8d5',
        'on-secondary-fixed': '#151f00',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'primary-fixed': '#c3ebd9',
        'on-background': '#1a1c19',
        outline: '#717974',
        'on-secondary': '#ffffff',
        'primary-container': '#13382c',
        'secondary-fixed': '#d4ec98',
        'surface-container-low': '#f3f4ef',
        'on-primary': '#ffffff',
        tertiary: '#0e2115',
        'on-primary-container': '#7ca292',
        'secondary-fixed-dim': '#b8d07e',
        background: '#f9faf5',
        'outline-variant': '#c1c8c3',
        'on-primary-fixed-variant': '#2a4d41',
        primary: '#002218',
        surface: '#f9faf5',
        'tertiary-container': '#233629',
        error: '#ba1a1a',
        'surface-bright': '#f9faf5',
        'on-tertiary-fixed': '#0d1f14',
        'inverse-surface': '#2e312e',
        'surface-container-high': '#e7e9e4',
        'on-tertiary-fixed-variant': '#384b3d',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#a8cfbe',
        'surface-container-highest': '#e2e3de',
        'inverse-on-surface': '#f0f1ec',
        'on-tertiary-container': '#8a9f8e',
        'on-primary-fixed': '#002117',
        'primary-fixed-dim': '#a8cfbe',
        'surface-container': '#edeee9',
        'secondary-container': '#d1e995',
        'on-surface-variant': '#414845',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Public Sans', 'sans-serif'],
        label: ['Public Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [forms],
}
